name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create parameter values JSON
    - env:
        SSH_ACCEPTED_SOURCES: ${{ secrets.SSH_ACCEPTED_SOURCES }}
        VALHEIM_ACCEPTED_SOURCES: ${{ secrets.VALHEIM_ACCEPTED_SOURCES }}
      run: |
        cat <<EOF > params.json
        {
          "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
          "contentVersion": "1.0.0.0",
          "parameters": {
            "valheim_server_password": {
              "value": "${{ secrets.VALHEIM_SERVER_PASSWORD }}"
            },
            "virtualMachine_sshPublicKey": {
              "value": "${{ secrets.SSH_PUBLIC_KEY }}"
            },
            "networkSecurityGroup_sshAcceptedSources": {
              "value": ${SSH_ACCEPTED_SOURCES:-'[]'}
            },
            "networkSecurityGroup_valheimAcceptedSources": {
              "value": ${VALHEIM_ACCEPTED_SOURCES:-'[]'}
            }
          }
        }
        EOF

    # Deploy Bicep file
    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: resources.bicep
        failOnStdErr: true
        parameters: params.json
